ProcessedMeasurement    measurement     # Measurements are in C.
---
bool                    success         # Indicated if the data was recorded
                                        # successfully.