ProcessedMeasurement    measurement     # Measurements are in C.
---
bool                    success         # Indicates if the data was recorded
                                        # successfully.